export const DUMMY_USERS = [
  {
    id: '0',
    name: 'Admin',
    surname: 'Admin',
    email: 'admin@gmail.com',
    password: 'admin',
    permissions: [],
  },
  {
    id: '1',
    name: 'Marko',
    surname: 'Markovic',
    email: 'marko.markovic@example.com',
    password: 'password123',
    permissions: [],
  },
  {
    id: '2',
    name: 'Jelena',
    surname: 'Jankovic',
    email: 'jelena.jankovic@example.com',
    password: 'password456',
    permissions: [],
  },
  {
    id: '3',
    name: 'Nikola',
    surname: 'Nikolic',
    email: 'nikola.nikolic@example.com',
    password: 'password789',
    permissions: [],
  },
  {
    id: '4',
    name: 'Ana',
    surname: 'Petrovic',
    email: 'ana.petrovic@example.com',
    password: 'password321',
    permissions: [],
  },
  {
    id: '5',
    name: 'Milan',
    surname: 'Ilic',
    email: 'milan.ilic@example.com',
    password: 'password654',
    permissions: [],
  },
  {
    id: '6',
    name: 'Sara',
    surname: 'Stojanovic',
    email: 'sara.stojanovic@example.com',
    password: 'password987',
    permissions: [],
  },
  {
    id: '7',
    name: 'Vuk',
    surname: 'Vukovic',
    email: 'vuk.vukovic@example.com',
    password: 'password159',
    permissions: [],
  },
  {
    id: '8',
    name: 'Teodora',
    surname: 'Milosevic',
    email: 'teodora.milosevic@example.com',
    password: 'password753',
    permissions: [],
  },
  {
    id: '9',
    name: 'Stefan',
    surname: 'Radovanovic',
    email: 'stefan.radovanovic@example.com',
    password: 'password852',
    permissions: [],
  },
  {
    id: '10',
    name: 'Marija',
    surname: 'Kostic',
    email: 'marija.kostic@example.com',
    password: 'password951',
    permissions: [],
  },
];
